version: "3.2"

services:
  database:
    image: docker.arvancloud.ir/mysql:8.4
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker_workshop_network
  server:
    build: .
    container_name: server_container
    ports:
      - 3000:3000
    networks:
      - docker_workshop_network
    environment:
      - MYSQL_URL=mysql://root:root@mysql_db/mysql
    depends_on:
      - database

networks:
  docker_workshop_network:
